// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)

namespace agv {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class AgvCommand;
class AgvTelemetry;
class CommonResponse;
class Heartbeat;
class LatencyProbe;
class MessageEnvelope;
class MpcTrajectory;
class NavigationTask;
class TaskFeedback;

// ===================================================================

class AgvTelemetry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agv.proto.AgvTelemetry) */ {
 public:
  AgvTelemetry();
  virtual ~AgvTelemetry();

  AgvTelemetry(const AgvTelemetry& from);

  inline AgvTelemetry& operator=(const AgvTelemetry& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AgvTelemetry& default_instance();

  void Swap(AgvTelemetry* other);

  // implements Message ----------------------------------------------

  inline AgvTelemetry* New() const { return New(NULL); }

  AgvTelemetry* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AgvTelemetry& from);
  void MergeFrom(const AgvTelemetry& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AgvTelemetry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string agv_id = 1;
  void clear_agv_id();
  static const int kAgvIdFieldNumber = 1;
  const ::std::string& agv_id() const;
  void set_agv_id(const ::std::string& value);
  void set_agv_id(const char* value);
  void set_agv_id(const char* value, size_t size);
  ::std::string* mutable_agv_id();
  ::std::string* release_agv_id();
  void set_allocated_agv_id(::std::string* agv_id);

  // optional int64 timestamp = 2;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // optional double x = 3;
  void clear_x();
  static const int kXFieldNumber = 3;
  double x() const;
  void set_x(double value);

  // optional double y = 4;
  void clear_y();
  static const int kYFieldNumber = 4;
  double y() const;
  void set_y(double value);

  // optional double theta = 5;
  void clear_theta();
  static const int kThetaFieldNumber = 5;
  double theta() const;
  void set_theta(double value);

  // optional double confidence = 6;
  void clear_confidence();
  static const int kConfidenceFieldNumber = 6;
  double confidence() const;
  void set_confidence(double value);

  // optional double linear_velocity = 7;
  void clear_linear_velocity();
  static const int kLinearVelocityFieldNumber = 7;
  double linear_velocity() const;
  void set_linear_velocity(double value);

  // optional double angular_velocity = 8;
  void clear_angular_velocity();
  static const int kAngularVelocityFieldNumber = 8;
  double angular_velocity() const;
  void set_angular_velocity(double value);

  // optional double acceleration = 9;
  void clear_acceleration();
  static const int kAccelerationFieldNumber = 9;
  double acceleration() const;
  void set_acceleration(double value);

  // optional double payload_weight = 10;
  void clear_payload_weight();
  static const int kPayloadWeightFieldNumber = 10;
  double payload_weight() const;
  void set_payload_weight(double value);

  // optional double battery = 11;
  void clear_battery();
  static const int kBatteryFieldNumber = 11;
  double battery() const;
  void set_battery(double value);

  // optional uint32 error_code = 12;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 12;
  ::google::protobuf::uint32 error_code() const;
  void set_error_code(::google::protobuf::uint32 value);

  // optional double fork_height = 13;
  void clear_fork_height();
  static const int kForkHeightFieldNumber = 13;
  double fork_height() const;
  void set_fork_height(double value);

  // @@protoc_insertion_point(class_scope:agv.proto.AgvTelemetry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr agv_id_;
  ::google::protobuf::int64 timestamp_;
  double x_;
  double y_;
  double theta_;
  double confidence_;
  double linear_velocity_;
  double angular_velocity_;
  double acceleration_;
  double payload_weight_;
  double battery_;
  double fork_height_;
  ::google::protobuf::uint32 error_code_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static AgvTelemetry* default_instance_;
};
// -------------------------------------------------------------------

class MpcTrajectory : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agv.proto.MpcTrajectory) */ {
 public:
  MpcTrajectory();
  virtual ~MpcTrajectory();

  MpcTrajectory(const MpcTrajectory& from);

  inline MpcTrajectory& operator=(const MpcTrajectory& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MpcTrajectory& default_instance();

  void Swap(MpcTrajectory* other);

  // implements Message ----------------------------------------------

  inline MpcTrajectory* New() const { return New(NULL); }

  MpcTrajectory* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MpcTrajectory& from);
  void MergeFrom(const MpcTrajectory& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MpcTrajectory* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string agv_id = 1;
  void clear_agv_id();
  static const int kAgvIdFieldNumber = 1;
  const ::std::string& agv_id() const;
  void set_agv_id(const ::std::string& value);
  void set_agv_id(const char* value);
  void set_agv_id(const char* value, size_t size);
  ::std::string* mutable_agv_id();
  ::std::string* release_agv_id();
  void set_allocated_agv_id(::std::string* agv_id);

  // optional int64 timestamp = 2;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // repeated .agv.proto.TimedPoint predicted_path = 3;
  int predicted_path_size() const;
  void clear_predicted_path();
  static const int kPredictedPathFieldNumber = 3;
  const ::agv::proto::TimedPoint& predicted_path(int index) const;
  ::agv::proto::TimedPoint* mutable_predicted_path(int index);
  ::agv::proto::TimedPoint* add_predicted_path();
  ::google::protobuf::RepeatedPtrField< ::agv::proto::TimedPoint >*
      mutable_predicted_path();
  const ::google::protobuf::RepeatedPtrField< ::agv::proto::TimedPoint >&
      predicted_path() const;

  // @@protoc_insertion_point(class_scope:agv.proto.MpcTrajectory)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr agv_id_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::RepeatedPtrField< ::agv::proto::TimedPoint > predicted_path_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static MpcTrajectory* default_instance_;
};
// -------------------------------------------------------------------

class TaskFeedback : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agv.proto.TaskFeedback) */ {
 public:
  TaskFeedback();
  virtual ~TaskFeedback();

  TaskFeedback(const TaskFeedback& from);

  inline TaskFeedback& operator=(const TaskFeedback& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TaskFeedback& default_instance();

  void Swap(TaskFeedback* other);

  // implements Message ----------------------------------------------

  inline TaskFeedback* New() const { return New(NULL); }

  TaskFeedback* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TaskFeedback& from);
  void MergeFrom(const TaskFeedback& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TaskFeedback* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string agv_id = 1;
  void clear_agv_id();
  static const int kAgvIdFieldNumber = 1;
  const ::std::string& agv_id() const;
  void set_agv_id(const ::std::string& value);
  void set_agv_id(const char* value);
  void set_agv_id(const char* value, size_t size);
  ::std::string* mutable_agv_id();
  ::std::string* release_agv_id();
  void set_allocated_agv_id(::std::string* agv_id);

  // optional int64 timestamp = 2;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // optional string task_id = 3;
  void clear_task_id();
  static const int kTaskIdFieldNumber = 3;
  const ::std::string& task_id() const;
  void set_task_id(const ::std::string& value);
  void set_task_id(const char* value);
  void set_task_id(const char* value, size_t size);
  ::std::string* mutable_task_id();
  ::std::string* release_task_id();
  void set_allocated_task_id(::std::string* task_id);

  // optional .agv.proto.TaskStatus status = 4;
  void clear_status();
  static const int kStatusFieldNumber = 4;
  ::agv::proto::TaskStatus status() const;
  void set_status(::agv::proto::TaskStatus value);

  // optional uint32 current_node_index = 5;
  void clear_current_node_index();
  static const int kCurrentNodeIndexFieldNumber = 5;
  ::google::protobuf::uint32 current_node_index() const;
  void set_current_node_index(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:agv.proto.TaskFeedback)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr agv_id_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::internal::ArenaStringPtr task_id_;
  int status_;
  ::google::protobuf::uint32 current_node_index_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static TaskFeedback* default_instance_;
};
// -------------------------------------------------------------------

class AgvCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agv.proto.AgvCommand) */ {
 public:
  AgvCommand();
  virtual ~AgvCommand();

  AgvCommand(const AgvCommand& from);

  inline AgvCommand& operator=(const AgvCommand& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AgvCommand& default_instance();

  void Swap(AgvCommand* other);

  // implements Message ----------------------------------------------

  inline AgvCommand* New() const { return New(NULL); }

  AgvCommand* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AgvCommand& from);
  void MergeFrom(const AgvCommand& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AgvCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string target_agv_id = 1;
  void clear_target_agv_id();
  static const int kTargetAgvIdFieldNumber = 1;
  const ::std::string& target_agv_id() const;
  void set_target_agv_id(const ::std::string& value);
  void set_target_agv_id(const char* value);
  void set_target_agv_id(const char* value, size_t size);
  ::std::string* mutable_target_agv_id();
  ::std::string* release_target_agv_id();
  void set_allocated_target_agv_id(::std::string* target_agv_id);

  // optional int64 timestamp = 2;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // optional .agv.proto.CommandType cmd_type = 3;
  void clear_cmd_type();
  static const int kCmdTypeFieldNumber = 3;
  ::agv::proto::CommandType cmd_type() const;
  void set_cmd_type(::agv::proto::CommandType value);

  // @@protoc_insertion_point(class_scope:agv.proto.AgvCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr target_agv_id_;
  ::google::protobuf::int64 timestamp_;
  int cmd_type_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static AgvCommand* default_instance_;
};
// -------------------------------------------------------------------

class NavigationTask : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agv.proto.NavigationTask) */ {
 public:
  NavigationTask();
  virtual ~NavigationTask();

  NavigationTask(const NavigationTask& from);

  inline NavigationTask& operator=(const NavigationTask& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NavigationTask& default_instance();

  void Swap(NavigationTask* other);

  // implements Message ----------------------------------------------

  inline NavigationTask* New() const { return New(NULL); }

  NavigationTask* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NavigationTask& from);
  void MergeFrom(const NavigationTask& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(NavigationTask* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string target_agv_id = 1;
  void clear_target_agv_id();
  static const int kTargetAgvIdFieldNumber = 1;
  const ::std::string& target_agv_id() const;
  void set_target_agv_id(const ::std::string& value);
  void set_target_agv_id(const char* value);
  void set_target_agv_id(const char* value, size_t size);
  ::std::string* mutable_target_agv_id();
  ::std::string* release_target_agv_id();
  void set_allocated_target_agv_id(::std::string* target_agv_id);

  // optional int64 timestamp = 2;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // optional string task_id = 3;
  void clear_task_id();
  static const int kTaskIdFieldNumber = 3;
  const ::std::string& task_id() const;
  void set_task_id(const ::std::string& value);
  void set_task_id(const char* value);
  void set_task_id(const char* value, size_t size);
  ::std::string* mutable_task_id();
  ::std::string* release_task_id();
  void set_allocated_task_id(::std::string* task_id);

  // optional .agv.proto.Point target_node = 4;
  bool has_target_node() const;
  void clear_target_node();
  static const int kTargetNodeFieldNumber = 4;
  const ::agv::proto::Point& target_node() const;
  ::agv::proto::Point* mutable_target_node();
  ::agv::proto::Point* release_target_node();
  void set_allocated_target_node(::agv::proto::Point* target_node);

  // optional .agv.proto.OperationType operation = 5;
  void clear_operation();
  static const int kOperationFieldNumber = 5;
  ::agv::proto::OperationType operation() const;
  void set_operation(::agv::proto::OperationType value);

  // repeated .agv.proto.Point global_path = 6;
  int global_path_size() const;
  void clear_global_path();
  static const int kGlobalPathFieldNumber = 6;
  const ::agv::proto::Point& global_path(int index) const;
  ::agv::proto::Point* mutable_global_path(int index);
  ::agv::proto::Point* add_global_path();
  ::google::protobuf::RepeatedPtrField< ::agv::proto::Point >*
      mutable_global_path();
  const ::google::protobuf::RepeatedPtrField< ::agv::proto::Point >&
      global_path() const;

  // @@protoc_insertion_point(class_scope:agv.proto.NavigationTask)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr target_agv_id_;
  ::google::protobuf::int64 timestamp_;
  ::google::protobuf::internal::ArenaStringPtr task_id_;
  ::agv::proto::Point* target_node_;
  ::google::protobuf::RepeatedPtrField< ::agv::proto::Point > global_path_;
  int operation_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static NavigationTask* default_instance_;
};
// -------------------------------------------------------------------

class LatencyProbe : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agv.proto.LatencyProbe) */ {
 public:
  LatencyProbe();
  virtual ~LatencyProbe();

  LatencyProbe(const LatencyProbe& from);

  inline LatencyProbe& operator=(const LatencyProbe& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LatencyProbe& default_instance();

  void Swap(LatencyProbe* other);

  // implements Message ----------------------------------------------

  inline LatencyProbe* New() const { return New(NULL); }

  LatencyProbe* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LatencyProbe& from);
  void MergeFrom(const LatencyProbe& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LatencyProbe* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string target_agv_id = 1;
  void clear_target_agv_id();
  static const int kTargetAgvIdFieldNumber = 1;
  const ::std::string& target_agv_id() const;
  void set_target_agv_id(const ::std::string& value);
  void set_target_agv_id(const char* value);
  void set_target_agv_id(const char* value, size_t size);
  ::std::string* mutable_target_agv_id();
  ::std::string* release_target_agv_id();
  void set_allocated_target_agv_id(::std::string* target_agv_id);

  // optional int64 send_timestamp = 2;
  void clear_send_timestamp();
  static const int kSendTimestampFieldNumber = 2;
  ::google::protobuf::int64 send_timestamp() const;
  void set_send_timestamp(::google::protobuf::int64 value);

  // optional uint64 seq_num = 3;
  void clear_seq_num();
  static const int kSeqNumFieldNumber = 3;
  ::google::protobuf::uint64 seq_num() const;
  void set_seq_num(::google::protobuf::uint64 value);

  // optional bool is_response = 4;
  void clear_is_response();
  static const int kIsResponseFieldNumber = 4;
  bool is_response() const;
  void set_is_response(bool value);

  // @@protoc_insertion_point(class_scope:agv.proto.LatencyProbe)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr target_agv_id_;
  ::google::protobuf::int64 send_timestamp_;
  ::google::protobuf::uint64 seq_num_;
  bool is_response_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static LatencyProbe* default_instance_;
};
// -------------------------------------------------------------------

class CommonResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agv.proto.CommonResponse) */ {
 public:
  CommonResponse();
  virtual ~CommonResponse();

  CommonResponse(const CommonResponse& from);

  inline CommonResponse& operator=(const CommonResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CommonResponse& default_instance();

  void Swap(CommonResponse* other);

  // implements Message ----------------------------------------------

  inline CommonResponse* New() const { return New(NULL); }

  CommonResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CommonResponse& from);
  void MergeFrom(const CommonResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CommonResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .agv.proto.StatusCode status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::agv::proto::StatusCode status() const;
  void set_status(::agv::proto::StatusCode value);

  // optional string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // optional int64 timestamp = 3;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:agv.proto.CommonResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int64 timestamp_;
  int status_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static CommonResponse* default_instance_;
};
// -------------------------------------------------------------------

class Heartbeat : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agv.proto.Heartbeat) */ {
 public:
  Heartbeat();
  virtual ~Heartbeat();

  Heartbeat(const Heartbeat& from);

  inline Heartbeat& operator=(const Heartbeat& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Heartbeat& default_instance();

  void Swap(Heartbeat* other);

  // implements Message ----------------------------------------------

  inline Heartbeat* New() const { return New(NULL); }

  Heartbeat* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Heartbeat& from);
  void MergeFrom(const Heartbeat& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Heartbeat* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string agv_id = 1;
  void clear_agv_id();
  static const int kAgvIdFieldNumber = 1;
  const ::std::string& agv_id() const;
  void set_agv_id(const ::std::string& value);
  void set_agv_id(const char* value);
  void set_agv_id(const char* value, size_t size);
  ::std::string* mutable_agv_id();
  ::std::string* release_agv_id();
  void set_allocated_agv_id(::std::string* agv_id);

  // optional int64 timestamp = 2;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:agv.proto.Heartbeat)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr agv_id_;
  ::google::protobuf::int64 timestamp_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static Heartbeat* default_instance_;
};
// -------------------------------------------------------------------

class MessageEnvelope : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:agv.proto.MessageEnvelope) */ {
 public:
  MessageEnvelope();
  virtual ~MessageEnvelope();

  MessageEnvelope(const MessageEnvelope& from);

  inline MessageEnvelope& operator=(const MessageEnvelope& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageEnvelope& default_instance();

  enum PayloadCase {
    kTelemetry = 1,
    kMpcTrajectory = 2,
    kTaskFeedback = 3,
    kCommand = 11,
    kNavTask = 12,
    kLatencyProbe = 13,
    kResponse = 21,
    kHeartbeat = 22,
    PAYLOAD_NOT_SET = 0,
  };

  void Swap(MessageEnvelope* other);

  // implements Message ----------------------------------------------

  inline MessageEnvelope* New() const { return New(NULL); }

  MessageEnvelope* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageEnvelope& from);
  void MergeFrom(const MessageEnvelope& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageEnvelope* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .agv.proto.AgvTelemetry telemetry = 1;
  bool has_telemetry() const;
  void clear_telemetry();
  static const int kTelemetryFieldNumber = 1;
  const ::agv::proto::AgvTelemetry& telemetry() const;
  ::agv::proto::AgvTelemetry* mutable_telemetry();
  ::agv::proto::AgvTelemetry* release_telemetry();
  void set_allocated_telemetry(::agv::proto::AgvTelemetry* telemetry);

  // optional .agv.proto.MpcTrajectory mpc_trajectory = 2;
  bool has_mpc_trajectory() const;
  void clear_mpc_trajectory();
  static const int kMpcTrajectoryFieldNumber = 2;
  const ::agv::proto::MpcTrajectory& mpc_trajectory() const;
  ::agv::proto::MpcTrajectory* mutable_mpc_trajectory();
  ::agv::proto::MpcTrajectory* release_mpc_trajectory();
  void set_allocated_mpc_trajectory(::agv::proto::MpcTrajectory* mpc_trajectory);

  // optional .agv.proto.TaskFeedback task_feedback = 3;
  bool has_task_feedback() const;
  void clear_task_feedback();
  static const int kTaskFeedbackFieldNumber = 3;
  const ::agv::proto::TaskFeedback& task_feedback() const;
  ::agv::proto::TaskFeedback* mutable_task_feedback();
  ::agv::proto::TaskFeedback* release_task_feedback();
  void set_allocated_task_feedback(::agv::proto::TaskFeedback* task_feedback);

  // optional .agv.proto.AgvCommand command = 11;
  bool has_command() const;
  void clear_command();
  static const int kCommandFieldNumber = 11;
  const ::agv::proto::AgvCommand& command() const;
  ::agv::proto::AgvCommand* mutable_command();
  ::agv::proto::AgvCommand* release_command();
  void set_allocated_command(::agv::proto::AgvCommand* command);

  // optional .agv.proto.NavigationTask nav_task = 12;
  bool has_nav_task() const;
  void clear_nav_task();
  static const int kNavTaskFieldNumber = 12;
  const ::agv::proto::NavigationTask& nav_task() const;
  ::agv::proto::NavigationTask* mutable_nav_task();
  ::agv::proto::NavigationTask* release_nav_task();
  void set_allocated_nav_task(::agv::proto::NavigationTask* nav_task);

  // optional .agv.proto.LatencyProbe latency_probe = 13;
  bool has_latency_probe() const;
  void clear_latency_probe();
  static const int kLatencyProbeFieldNumber = 13;
  const ::agv::proto::LatencyProbe& latency_probe() const;
  ::agv::proto::LatencyProbe* mutable_latency_probe();
  ::agv::proto::LatencyProbe* release_latency_probe();
  void set_allocated_latency_probe(::agv::proto::LatencyProbe* latency_probe);

  // optional .agv.proto.CommonResponse response = 21;
  bool has_response() const;
  void clear_response();
  static const int kResponseFieldNumber = 21;
  const ::agv::proto::CommonResponse& response() const;
  ::agv::proto::CommonResponse* mutable_response();
  ::agv::proto::CommonResponse* release_response();
  void set_allocated_response(::agv::proto::CommonResponse* response);

  // optional .agv.proto.Heartbeat heartbeat = 22;
  bool has_heartbeat() const;
  void clear_heartbeat();
  static const int kHeartbeatFieldNumber = 22;
  const ::agv::proto::Heartbeat& heartbeat() const;
  ::agv::proto::Heartbeat* mutable_heartbeat();
  ::agv::proto::Heartbeat* release_heartbeat();
  void set_allocated_heartbeat(::agv::proto::Heartbeat* heartbeat);

  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:agv.proto.MessageEnvelope)
 private:
  inline void set_has_telemetry();
  inline void set_has_mpc_trajectory();
  inline void set_has_task_feedback();
  inline void set_has_command();
  inline void set_has_nav_task();
  inline void set_has_latency_probe();
  inline void set_has_response();
  inline void set_has_heartbeat();

  inline bool has_payload() const;
  void clear_payload();
  inline void clear_has_payload();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  union PayloadUnion {
    PayloadUnion() {}
    ::agv::proto::AgvTelemetry* telemetry_;
    ::agv::proto::MpcTrajectory* mpc_trajectory_;
    ::agv::proto::TaskFeedback* task_feedback_;
    ::agv::proto::AgvCommand* command_;
    ::agv::proto::NavigationTask* nav_task_;
    ::agv::proto::LatencyProbe* latency_probe_;
    ::agv::proto::CommonResponse* response_;
    ::agv::proto::Heartbeat* heartbeat_;
  } payload_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static MessageEnvelope* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// AgvTelemetry

// optional string agv_id = 1;
inline void AgvTelemetry::clear_agv_id() {
  agv_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AgvTelemetry::agv_id() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.agv_id)
  return agv_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AgvTelemetry::set_agv_id(const ::std::string& value) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.agv_id)
}
inline void AgvTelemetry::set_agv_id(const char* value) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agv.proto.AgvTelemetry.agv_id)
}
inline void AgvTelemetry::set_agv_id(const char* value, size_t size) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agv.proto.AgvTelemetry.agv_id)
}
inline ::std::string* AgvTelemetry::mutable_agv_id() {
  
  // @@protoc_insertion_point(field_mutable:agv.proto.AgvTelemetry.agv_id)
  return agv_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AgvTelemetry::release_agv_id() {
  // @@protoc_insertion_point(field_release:agv.proto.AgvTelemetry.agv_id)
  
  return agv_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AgvTelemetry::set_allocated_agv_id(::std::string* agv_id) {
  if (agv_id != NULL) {
    
  } else {
    
  }
  agv_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), agv_id);
  // @@protoc_insertion_point(field_set_allocated:agv.proto.AgvTelemetry.agv_id)
}

// optional int64 timestamp = 2;
inline void AgvTelemetry::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 AgvTelemetry::timestamp() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.timestamp)
  return timestamp_;
}
inline void AgvTelemetry::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.timestamp)
}

// optional double x = 3;
inline void AgvTelemetry::clear_x() {
  x_ = 0;
}
inline double AgvTelemetry::x() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.x)
  return x_;
}
inline void AgvTelemetry::set_x(double value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.x)
}

// optional double y = 4;
inline void AgvTelemetry::clear_y() {
  y_ = 0;
}
inline double AgvTelemetry::y() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.y)
  return y_;
}
inline void AgvTelemetry::set_y(double value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.y)
}

// optional double theta = 5;
inline void AgvTelemetry::clear_theta() {
  theta_ = 0;
}
inline double AgvTelemetry::theta() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.theta)
  return theta_;
}
inline void AgvTelemetry::set_theta(double value) {
  
  theta_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.theta)
}

// optional double confidence = 6;
inline void AgvTelemetry::clear_confidence() {
  confidence_ = 0;
}
inline double AgvTelemetry::confidence() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.confidence)
  return confidence_;
}
inline void AgvTelemetry::set_confidence(double value) {
  
  confidence_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.confidence)
}

// optional double linear_velocity = 7;
inline void AgvTelemetry::clear_linear_velocity() {
  linear_velocity_ = 0;
}
inline double AgvTelemetry::linear_velocity() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.linear_velocity)
  return linear_velocity_;
}
inline void AgvTelemetry::set_linear_velocity(double value) {
  
  linear_velocity_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.linear_velocity)
}

// optional double angular_velocity = 8;
inline void AgvTelemetry::clear_angular_velocity() {
  angular_velocity_ = 0;
}
inline double AgvTelemetry::angular_velocity() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.angular_velocity)
  return angular_velocity_;
}
inline void AgvTelemetry::set_angular_velocity(double value) {
  
  angular_velocity_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.angular_velocity)
}

// optional double acceleration = 9;
inline void AgvTelemetry::clear_acceleration() {
  acceleration_ = 0;
}
inline double AgvTelemetry::acceleration() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.acceleration)
  return acceleration_;
}
inline void AgvTelemetry::set_acceleration(double value) {
  
  acceleration_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.acceleration)
}

// optional double payload_weight = 10;
inline void AgvTelemetry::clear_payload_weight() {
  payload_weight_ = 0;
}
inline double AgvTelemetry::payload_weight() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.payload_weight)
  return payload_weight_;
}
inline void AgvTelemetry::set_payload_weight(double value) {
  
  payload_weight_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.payload_weight)
}

// optional double battery = 11;
inline void AgvTelemetry::clear_battery() {
  battery_ = 0;
}
inline double AgvTelemetry::battery() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.battery)
  return battery_;
}
inline void AgvTelemetry::set_battery(double value) {
  
  battery_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.battery)
}

// optional uint32 error_code = 12;
inline void AgvTelemetry::clear_error_code() {
  error_code_ = 0u;
}
inline ::google::protobuf::uint32 AgvTelemetry::error_code() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.error_code)
  return error_code_;
}
inline void AgvTelemetry::set_error_code(::google::protobuf::uint32 value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.error_code)
}

// optional double fork_height = 13;
inline void AgvTelemetry::clear_fork_height() {
  fork_height_ = 0;
}
inline double AgvTelemetry::fork_height() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvTelemetry.fork_height)
  return fork_height_;
}
inline void AgvTelemetry::set_fork_height(double value) {
  
  fork_height_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvTelemetry.fork_height)
}

// -------------------------------------------------------------------

// MpcTrajectory

// optional string agv_id = 1;
inline void MpcTrajectory::clear_agv_id() {
  agv_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MpcTrajectory::agv_id() const {
  // @@protoc_insertion_point(field_get:agv.proto.MpcTrajectory.agv_id)
  return agv_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MpcTrajectory::set_agv_id(const ::std::string& value) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agv.proto.MpcTrajectory.agv_id)
}
inline void MpcTrajectory::set_agv_id(const char* value) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agv.proto.MpcTrajectory.agv_id)
}
inline void MpcTrajectory::set_agv_id(const char* value, size_t size) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agv.proto.MpcTrajectory.agv_id)
}
inline ::std::string* MpcTrajectory::mutable_agv_id() {
  
  // @@protoc_insertion_point(field_mutable:agv.proto.MpcTrajectory.agv_id)
  return agv_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MpcTrajectory::release_agv_id() {
  // @@protoc_insertion_point(field_release:agv.proto.MpcTrajectory.agv_id)
  
  return agv_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MpcTrajectory::set_allocated_agv_id(::std::string* agv_id) {
  if (agv_id != NULL) {
    
  } else {
    
  }
  agv_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), agv_id);
  // @@protoc_insertion_point(field_set_allocated:agv.proto.MpcTrajectory.agv_id)
}

// optional int64 timestamp = 2;
inline void MpcTrajectory::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 MpcTrajectory::timestamp() const {
  // @@protoc_insertion_point(field_get:agv.proto.MpcTrajectory.timestamp)
  return timestamp_;
}
inline void MpcTrajectory::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.MpcTrajectory.timestamp)
}

// repeated .agv.proto.TimedPoint predicted_path = 3;
inline int MpcTrajectory::predicted_path_size() const {
  return predicted_path_.size();
}
inline void MpcTrajectory::clear_predicted_path() {
  predicted_path_.Clear();
}
inline const ::agv::proto::TimedPoint& MpcTrajectory::predicted_path(int index) const {
  // @@protoc_insertion_point(field_get:agv.proto.MpcTrajectory.predicted_path)
  return predicted_path_.Get(index);
}
inline ::agv::proto::TimedPoint* MpcTrajectory::mutable_predicted_path(int index) {
  // @@protoc_insertion_point(field_mutable:agv.proto.MpcTrajectory.predicted_path)
  return predicted_path_.Mutable(index);
}
inline ::agv::proto::TimedPoint* MpcTrajectory::add_predicted_path() {
  // @@protoc_insertion_point(field_add:agv.proto.MpcTrajectory.predicted_path)
  return predicted_path_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::agv::proto::TimedPoint >*
MpcTrajectory::mutable_predicted_path() {
  // @@protoc_insertion_point(field_mutable_list:agv.proto.MpcTrajectory.predicted_path)
  return &predicted_path_;
}
inline const ::google::protobuf::RepeatedPtrField< ::agv::proto::TimedPoint >&
MpcTrajectory::predicted_path() const {
  // @@protoc_insertion_point(field_list:agv.proto.MpcTrajectory.predicted_path)
  return predicted_path_;
}

// -------------------------------------------------------------------

// TaskFeedback

// optional string agv_id = 1;
inline void TaskFeedback::clear_agv_id() {
  agv_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TaskFeedback::agv_id() const {
  // @@protoc_insertion_point(field_get:agv.proto.TaskFeedback.agv_id)
  return agv_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TaskFeedback::set_agv_id(const ::std::string& value) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agv.proto.TaskFeedback.agv_id)
}
inline void TaskFeedback::set_agv_id(const char* value) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agv.proto.TaskFeedback.agv_id)
}
inline void TaskFeedback::set_agv_id(const char* value, size_t size) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agv.proto.TaskFeedback.agv_id)
}
inline ::std::string* TaskFeedback::mutable_agv_id() {
  
  // @@protoc_insertion_point(field_mutable:agv.proto.TaskFeedback.agv_id)
  return agv_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TaskFeedback::release_agv_id() {
  // @@protoc_insertion_point(field_release:agv.proto.TaskFeedback.agv_id)
  
  return agv_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TaskFeedback::set_allocated_agv_id(::std::string* agv_id) {
  if (agv_id != NULL) {
    
  } else {
    
  }
  agv_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), agv_id);
  // @@protoc_insertion_point(field_set_allocated:agv.proto.TaskFeedback.agv_id)
}

// optional int64 timestamp = 2;
inline void TaskFeedback::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 TaskFeedback::timestamp() const {
  // @@protoc_insertion_point(field_get:agv.proto.TaskFeedback.timestamp)
  return timestamp_;
}
inline void TaskFeedback::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.TaskFeedback.timestamp)
}

// optional string task_id = 3;
inline void TaskFeedback::clear_task_id() {
  task_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TaskFeedback::task_id() const {
  // @@protoc_insertion_point(field_get:agv.proto.TaskFeedback.task_id)
  return task_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TaskFeedback::set_task_id(const ::std::string& value) {
  
  task_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agv.proto.TaskFeedback.task_id)
}
inline void TaskFeedback::set_task_id(const char* value) {
  
  task_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agv.proto.TaskFeedback.task_id)
}
inline void TaskFeedback::set_task_id(const char* value, size_t size) {
  
  task_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agv.proto.TaskFeedback.task_id)
}
inline ::std::string* TaskFeedback::mutable_task_id() {
  
  // @@protoc_insertion_point(field_mutable:agv.proto.TaskFeedback.task_id)
  return task_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TaskFeedback::release_task_id() {
  // @@protoc_insertion_point(field_release:agv.proto.TaskFeedback.task_id)
  
  return task_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TaskFeedback::set_allocated_task_id(::std::string* task_id) {
  if (task_id != NULL) {
    
  } else {
    
  }
  task_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), task_id);
  // @@protoc_insertion_point(field_set_allocated:agv.proto.TaskFeedback.task_id)
}

// optional .agv.proto.TaskStatus status = 4;
inline void TaskFeedback::clear_status() {
  status_ = 0;
}
inline ::agv::proto::TaskStatus TaskFeedback::status() const {
  // @@protoc_insertion_point(field_get:agv.proto.TaskFeedback.status)
  return static_cast< ::agv::proto::TaskStatus >(status_);
}
inline void TaskFeedback::set_status(::agv::proto::TaskStatus value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.TaskFeedback.status)
}

// optional uint32 current_node_index = 5;
inline void TaskFeedback::clear_current_node_index() {
  current_node_index_ = 0u;
}
inline ::google::protobuf::uint32 TaskFeedback::current_node_index() const {
  // @@protoc_insertion_point(field_get:agv.proto.TaskFeedback.current_node_index)
  return current_node_index_;
}
inline void TaskFeedback::set_current_node_index(::google::protobuf::uint32 value) {
  
  current_node_index_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.TaskFeedback.current_node_index)
}

// -------------------------------------------------------------------

// AgvCommand

// optional string target_agv_id = 1;
inline void AgvCommand::clear_target_agv_id() {
  target_agv_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AgvCommand::target_agv_id() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvCommand.target_agv_id)
  return target_agv_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AgvCommand::set_target_agv_id(const ::std::string& value) {
  
  target_agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agv.proto.AgvCommand.target_agv_id)
}
inline void AgvCommand::set_target_agv_id(const char* value) {
  
  target_agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agv.proto.AgvCommand.target_agv_id)
}
inline void AgvCommand::set_target_agv_id(const char* value, size_t size) {
  
  target_agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agv.proto.AgvCommand.target_agv_id)
}
inline ::std::string* AgvCommand::mutable_target_agv_id() {
  
  // @@protoc_insertion_point(field_mutable:agv.proto.AgvCommand.target_agv_id)
  return target_agv_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AgvCommand::release_target_agv_id() {
  // @@protoc_insertion_point(field_release:agv.proto.AgvCommand.target_agv_id)
  
  return target_agv_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AgvCommand::set_allocated_target_agv_id(::std::string* target_agv_id) {
  if (target_agv_id != NULL) {
    
  } else {
    
  }
  target_agv_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), target_agv_id);
  // @@protoc_insertion_point(field_set_allocated:agv.proto.AgvCommand.target_agv_id)
}

// optional int64 timestamp = 2;
inline void AgvCommand::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 AgvCommand::timestamp() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvCommand.timestamp)
  return timestamp_;
}
inline void AgvCommand::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvCommand.timestamp)
}

// optional .agv.proto.CommandType cmd_type = 3;
inline void AgvCommand::clear_cmd_type() {
  cmd_type_ = 0;
}
inline ::agv::proto::CommandType AgvCommand::cmd_type() const {
  // @@protoc_insertion_point(field_get:agv.proto.AgvCommand.cmd_type)
  return static_cast< ::agv::proto::CommandType >(cmd_type_);
}
inline void AgvCommand::set_cmd_type(::agv::proto::CommandType value) {
  
  cmd_type_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.AgvCommand.cmd_type)
}

// -------------------------------------------------------------------

// NavigationTask

// optional string target_agv_id = 1;
inline void NavigationTask::clear_target_agv_id() {
  target_agv_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NavigationTask::target_agv_id() const {
  // @@protoc_insertion_point(field_get:agv.proto.NavigationTask.target_agv_id)
  return target_agv_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NavigationTask::set_target_agv_id(const ::std::string& value) {
  
  target_agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agv.proto.NavigationTask.target_agv_id)
}
inline void NavigationTask::set_target_agv_id(const char* value) {
  
  target_agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agv.proto.NavigationTask.target_agv_id)
}
inline void NavigationTask::set_target_agv_id(const char* value, size_t size) {
  
  target_agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agv.proto.NavigationTask.target_agv_id)
}
inline ::std::string* NavigationTask::mutable_target_agv_id() {
  
  // @@protoc_insertion_point(field_mutable:agv.proto.NavigationTask.target_agv_id)
  return target_agv_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NavigationTask::release_target_agv_id() {
  // @@protoc_insertion_point(field_release:agv.proto.NavigationTask.target_agv_id)
  
  return target_agv_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NavigationTask::set_allocated_target_agv_id(::std::string* target_agv_id) {
  if (target_agv_id != NULL) {
    
  } else {
    
  }
  target_agv_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), target_agv_id);
  // @@protoc_insertion_point(field_set_allocated:agv.proto.NavigationTask.target_agv_id)
}

// optional int64 timestamp = 2;
inline void NavigationTask::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 NavigationTask::timestamp() const {
  // @@protoc_insertion_point(field_get:agv.proto.NavigationTask.timestamp)
  return timestamp_;
}
inline void NavigationTask::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.NavigationTask.timestamp)
}

// optional string task_id = 3;
inline void NavigationTask::clear_task_id() {
  task_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NavigationTask::task_id() const {
  // @@protoc_insertion_point(field_get:agv.proto.NavigationTask.task_id)
  return task_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NavigationTask::set_task_id(const ::std::string& value) {
  
  task_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agv.proto.NavigationTask.task_id)
}
inline void NavigationTask::set_task_id(const char* value) {
  
  task_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agv.proto.NavigationTask.task_id)
}
inline void NavigationTask::set_task_id(const char* value, size_t size) {
  
  task_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agv.proto.NavigationTask.task_id)
}
inline ::std::string* NavigationTask::mutable_task_id() {
  
  // @@protoc_insertion_point(field_mutable:agv.proto.NavigationTask.task_id)
  return task_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NavigationTask::release_task_id() {
  // @@protoc_insertion_point(field_release:agv.proto.NavigationTask.task_id)
  
  return task_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NavigationTask::set_allocated_task_id(::std::string* task_id) {
  if (task_id != NULL) {
    
  } else {
    
  }
  task_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), task_id);
  // @@protoc_insertion_point(field_set_allocated:agv.proto.NavigationTask.task_id)
}

// optional .agv.proto.Point target_node = 4;
inline bool NavigationTask::has_target_node() const {
  return !_is_default_instance_ && target_node_ != NULL;
}
inline void NavigationTask::clear_target_node() {
  if (GetArenaNoVirtual() == NULL && target_node_ != NULL) delete target_node_;
  target_node_ = NULL;
}
inline const ::agv::proto::Point& NavigationTask::target_node() const {
  // @@protoc_insertion_point(field_get:agv.proto.NavigationTask.target_node)
  return target_node_ != NULL ? *target_node_ : *default_instance_->target_node_;
}
inline ::agv::proto::Point* NavigationTask::mutable_target_node() {
  
  if (target_node_ == NULL) {
    target_node_ = new ::agv::proto::Point;
  }
  // @@protoc_insertion_point(field_mutable:agv.proto.NavigationTask.target_node)
  return target_node_;
}
inline ::agv::proto::Point* NavigationTask::release_target_node() {
  // @@protoc_insertion_point(field_release:agv.proto.NavigationTask.target_node)
  
  ::agv::proto::Point* temp = target_node_;
  target_node_ = NULL;
  return temp;
}
inline void NavigationTask::set_allocated_target_node(::agv::proto::Point* target_node) {
  delete target_node_;
  target_node_ = target_node;
  if (target_node) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:agv.proto.NavigationTask.target_node)
}

// optional .agv.proto.OperationType operation = 5;
inline void NavigationTask::clear_operation() {
  operation_ = 0;
}
inline ::agv::proto::OperationType NavigationTask::operation() const {
  // @@protoc_insertion_point(field_get:agv.proto.NavigationTask.operation)
  return static_cast< ::agv::proto::OperationType >(operation_);
}
inline void NavigationTask::set_operation(::agv::proto::OperationType value) {
  
  operation_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.NavigationTask.operation)
}

// repeated .agv.proto.Point global_path = 6;
inline int NavigationTask::global_path_size() const {
  return global_path_.size();
}
inline void NavigationTask::clear_global_path() {
  global_path_.Clear();
}
inline const ::agv::proto::Point& NavigationTask::global_path(int index) const {
  // @@protoc_insertion_point(field_get:agv.proto.NavigationTask.global_path)
  return global_path_.Get(index);
}
inline ::agv::proto::Point* NavigationTask::mutable_global_path(int index) {
  // @@protoc_insertion_point(field_mutable:agv.proto.NavigationTask.global_path)
  return global_path_.Mutable(index);
}
inline ::agv::proto::Point* NavigationTask::add_global_path() {
  // @@protoc_insertion_point(field_add:agv.proto.NavigationTask.global_path)
  return global_path_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::agv::proto::Point >*
NavigationTask::mutable_global_path() {
  // @@protoc_insertion_point(field_mutable_list:agv.proto.NavigationTask.global_path)
  return &global_path_;
}
inline const ::google::protobuf::RepeatedPtrField< ::agv::proto::Point >&
NavigationTask::global_path() const {
  // @@protoc_insertion_point(field_list:agv.proto.NavigationTask.global_path)
  return global_path_;
}

// -------------------------------------------------------------------

// LatencyProbe

// optional string target_agv_id = 1;
inline void LatencyProbe::clear_target_agv_id() {
  target_agv_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& LatencyProbe::target_agv_id() const {
  // @@protoc_insertion_point(field_get:agv.proto.LatencyProbe.target_agv_id)
  return target_agv_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LatencyProbe::set_target_agv_id(const ::std::string& value) {
  
  target_agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agv.proto.LatencyProbe.target_agv_id)
}
inline void LatencyProbe::set_target_agv_id(const char* value) {
  
  target_agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agv.proto.LatencyProbe.target_agv_id)
}
inline void LatencyProbe::set_target_agv_id(const char* value, size_t size) {
  
  target_agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agv.proto.LatencyProbe.target_agv_id)
}
inline ::std::string* LatencyProbe::mutable_target_agv_id() {
  
  // @@protoc_insertion_point(field_mutable:agv.proto.LatencyProbe.target_agv_id)
  return target_agv_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LatencyProbe::release_target_agv_id() {
  // @@protoc_insertion_point(field_release:agv.proto.LatencyProbe.target_agv_id)
  
  return target_agv_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LatencyProbe::set_allocated_target_agv_id(::std::string* target_agv_id) {
  if (target_agv_id != NULL) {
    
  } else {
    
  }
  target_agv_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), target_agv_id);
  // @@protoc_insertion_point(field_set_allocated:agv.proto.LatencyProbe.target_agv_id)
}

// optional int64 send_timestamp = 2;
inline void LatencyProbe::clear_send_timestamp() {
  send_timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 LatencyProbe::send_timestamp() const {
  // @@protoc_insertion_point(field_get:agv.proto.LatencyProbe.send_timestamp)
  return send_timestamp_;
}
inline void LatencyProbe::set_send_timestamp(::google::protobuf::int64 value) {
  
  send_timestamp_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.LatencyProbe.send_timestamp)
}

// optional uint64 seq_num = 3;
inline void LatencyProbe::clear_seq_num() {
  seq_num_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 LatencyProbe::seq_num() const {
  // @@protoc_insertion_point(field_get:agv.proto.LatencyProbe.seq_num)
  return seq_num_;
}
inline void LatencyProbe::set_seq_num(::google::protobuf::uint64 value) {
  
  seq_num_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.LatencyProbe.seq_num)
}

// optional bool is_response = 4;
inline void LatencyProbe::clear_is_response() {
  is_response_ = false;
}
inline bool LatencyProbe::is_response() const {
  // @@protoc_insertion_point(field_get:agv.proto.LatencyProbe.is_response)
  return is_response_;
}
inline void LatencyProbe::set_is_response(bool value) {
  
  is_response_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.LatencyProbe.is_response)
}

// -------------------------------------------------------------------

// CommonResponse

// optional .agv.proto.StatusCode status = 1;
inline void CommonResponse::clear_status() {
  status_ = 0;
}
inline ::agv::proto::StatusCode CommonResponse::status() const {
  // @@protoc_insertion_point(field_get:agv.proto.CommonResponse.status)
  return static_cast< ::agv::proto::StatusCode >(status_);
}
inline void CommonResponse::set_status(::agv::proto::StatusCode value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.CommonResponse.status)
}

// optional string message = 2;
inline void CommonResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CommonResponse::message() const {
  // @@protoc_insertion_point(field_get:agv.proto.CommonResponse.message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CommonResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agv.proto.CommonResponse.message)
}
inline void CommonResponse::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agv.proto.CommonResponse.message)
}
inline void CommonResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agv.proto.CommonResponse.message)
}
inline ::std::string* CommonResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:agv.proto.CommonResponse.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CommonResponse::release_message() {
  // @@protoc_insertion_point(field_release:agv.proto.CommonResponse.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CommonResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:agv.proto.CommonResponse.message)
}

// optional int64 timestamp = 3;
inline void CommonResponse::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 CommonResponse::timestamp() const {
  // @@protoc_insertion_point(field_get:agv.proto.CommonResponse.timestamp)
  return timestamp_;
}
inline void CommonResponse::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.CommonResponse.timestamp)
}

// -------------------------------------------------------------------

// Heartbeat

// optional string agv_id = 1;
inline void Heartbeat::clear_agv_id() {
  agv_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Heartbeat::agv_id() const {
  // @@protoc_insertion_point(field_get:agv.proto.Heartbeat.agv_id)
  return agv_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Heartbeat::set_agv_id(const ::std::string& value) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:agv.proto.Heartbeat.agv_id)
}
inline void Heartbeat::set_agv_id(const char* value) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:agv.proto.Heartbeat.agv_id)
}
inline void Heartbeat::set_agv_id(const char* value, size_t size) {
  
  agv_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:agv.proto.Heartbeat.agv_id)
}
inline ::std::string* Heartbeat::mutable_agv_id() {
  
  // @@protoc_insertion_point(field_mutable:agv.proto.Heartbeat.agv_id)
  return agv_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Heartbeat::release_agv_id() {
  // @@protoc_insertion_point(field_release:agv.proto.Heartbeat.agv_id)
  
  return agv_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Heartbeat::set_allocated_agv_id(::std::string* agv_id) {
  if (agv_id != NULL) {
    
  } else {
    
  }
  agv_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), agv_id);
  // @@protoc_insertion_point(field_set_allocated:agv.proto.Heartbeat.agv_id)
}

// optional int64 timestamp = 2;
inline void Heartbeat::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Heartbeat::timestamp() const {
  // @@protoc_insertion_point(field_get:agv.proto.Heartbeat.timestamp)
  return timestamp_;
}
inline void Heartbeat::set_timestamp(::google::protobuf::int64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:agv.proto.Heartbeat.timestamp)
}

// -------------------------------------------------------------------

// MessageEnvelope

// optional .agv.proto.AgvTelemetry telemetry = 1;
inline bool MessageEnvelope::has_telemetry() const {
  return payload_case() == kTelemetry;
}
inline void MessageEnvelope::set_has_telemetry() {
  _oneof_case_[0] = kTelemetry;
}
inline void MessageEnvelope::clear_telemetry() {
  if (has_telemetry()) {
    delete payload_.telemetry_;
    clear_has_payload();
  }
}
inline  const ::agv::proto::AgvTelemetry& MessageEnvelope::telemetry() const {
  // @@protoc_insertion_point(field_get:agv.proto.MessageEnvelope.telemetry)
  return has_telemetry()
      ? *payload_.telemetry_
      : ::agv::proto::AgvTelemetry::default_instance();
}
inline ::agv::proto::AgvTelemetry* MessageEnvelope::mutable_telemetry() {
  if (!has_telemetry()) {
    clear_payload();
    set_has_telemetry();
    payload_.telemetry_ = new ::agv::proto::AgvTelemetry;
  }
  // @@protoc_insertion_point(field_mutable:agv.proto.MessageEnvelope.telemetry)
  return payload_.telemetry_;
}
inline ::agv::proto::AgvTelemetry* MessageEnvelope::release_telemetry() {
  // @@protoc_insertion_point(field_release:agv.proto.MessageEnvelope.telemetry)
  if (has_telemetry()) {
    clear_has_payload();
    ::agv::proto::AgvTelemetry* temp = payload_.telemetry_;
    payload_.telemetry_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void MessageEnvelope::set_allocated_telemetry(::agv::proto::AgvTelemetry* telemetry) {
  clear_payload();
  if (telemetry) {
    set_has_telemetry();
    payload_.telemetry_ = telemetry;
  }
  // @@protoc_insertion_point(field_set_allocated:agv.proto.MessageEnvelope.telemetry)
}

// optional .agv.proto.MpcTrajectory mpc_trajectory = 2;
inline bool MessageEnvelope::has_mpc_trajectory() const {
  return payload_case() == kMpcTrajectory;
}
inline void MessageEnvelope::set_has_mpc_trajectory() {
  _oneof_case_[0] = kMpcTrajectory;
}
inline void MessageEnvelope::clear_mpc_trajectory() {
  if (has_mpc_trajectory()) {
    delete payload_.mpc_trajectory_;
    clear_has_payload();
  }
}
inline  const ::agv::proto::MpcTrajectory& MessageEnvelope::mpc_trajectory() const {
  // @@protoc_insertion_point(field_get:agv.proto.MessageEnvelope.mpc_trajectory)
  return has_mpc_trajectory()
      ? *payload_.mpc_trajectory_
      : ::agv::proto::MpcTrajectory::default_instance();
}
inline ::agv::proto::MpcTrajectory* MessageEnvelope::mutable_mpc_trajectory() {
  if (!has_mpc_trajectory()) {
    clear_payload();
    set_has_mpc_trajectory();
    payload_.mpc_trajectory_ = new ::agv::proto::MpcTrajectory;
  }
  // @@protoc_insertion_point(field_mutable:agv.proto.MessageEnvelope.mpc_trajectory)
  return payload_.mpc_trajectory_;
}
inline ::agv::proto::MpcTrajectory* MessageEnvelope::release_mpc_trajectory() {
  // @@protoc_insertion_point(field_release:agv.proto.MessageEnvelope.mpc_trajectory)
  if (has_mpc_trajectory()) {
    clear_has_payload();
    ::agv::proto::MpcTrajectory* temp = payload_.mpc_trajectory_;
    payload_.mpc_trajectory_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void MessageEnvelope::set_allocated_mpc_trajectory(::agv::proto::MpcTrajectory* mpc_trajectory) {
  clear_payload();
  if (mpc_trajectory) {
    set_has_mpc_trajectory();
    payload_.mpc_trajectory_ = mpc_trajectory;
  }
  // @@protoc_insertion_point(field_set_allocated:agv.proto.MessageEnvelope.mpc_trajectory)
}

// optional .agv.proto.TaskFeedback task_feedback = 3;
inline bool MessageEnvelope::has_task_feedback() const {
  return payload_case() == kTaskFeedback;
}
inline void MessageEnvelope::set_has_task_feedback() {
  _oneof_case_[0] = kTaskFeedback;
}
inline void MessageEnvelope::clear_task_feedback() {
  if (has_task_feedback()) {
    delete payload_.task_feedback_;
    clear_has_payload();
  }
}
inline  const ::agv::proto::TaskFeedback& MessageEnvelope::task_feedback() const {
  // @@protoc_insertion_point(field_get:agv.proto.MessageEnvelope.task_feedback)
  return has_task_feedback()
      ? *payload_.task_feedback_
      : ::agv::proto::TaskFeedback::default_instance();
}
inline ::agv::proto::TaskFeedback* MessageEnvelope::mutable_task_feedback() {
  if (!has_task_feedback()) {
    clear_payload();
    set_has_task_feedback();
    payload_.task_feedback_ = new ::agv::proto::TaskFeedback;
  }
  // @@protoc_insertion_point(field_mutable:agv.proto.MessageEnvelope.task_feedback)
  return payload_.task_feedback_;
}
inline ::agv::proto::TaskFeedback* MessageEnvelope::release_task_feedback() {
  // @@protoc_insertion_point(field_release:agv.proto.MessageEnvelope.task_feedback)
  if (has_task_feedback()) {
    clear_has_payload();
    ::agv::proto::TaskFeedback* temp = payload_.task_feedback_;
    payload_.task_feedback_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void MessageEnvelope::set_allocated_task_feedback(::agv::proto::TaskFeedback* task_feedback) {
  clear_payload();
  if (task_feedback) {
    set_has_task_feedback();
    payload_.task_feedback_ = task_feedback;
  }
  // @@protoc_insertion_point(field_set_allocated:agv.proto.MessageEnvelope.task_feedback)
}

// optional .agv.proto.AgvCommand command = 11;
inline bool MessageEnvelope::has_command() const {
  return payload_case() == kCommand;
}
inline void MessageEnvelope::set_has_command() {
  _oneof_case_[0] = kCommand;
}
inline void MessageEnvelope::clear_command() {
  if (has_command()) {
    delete payload_.command_;
    clear_has_payload();
  }
}
inline  const ::agv::proto::AgvCommand& MessageEnvelope::command() const {
  // @@protoc_insertion_point(field_get:agv.proto.MessageEnvelope.command)
  return has_command()
      ? *payload_.command_
      : ::agv::proto::AgvCommand::default_instance();
}
inline ::agv::proto::AgvCommand* MessageEnvelope::mutable_command() {
  if (!has_command()) {
    clear_payload();
    set_has_command();
    payload_.command_ = new ::agv::proto::AgvCommand;
  }
  // @@protoc_insertion_point(field_mutable:agv.proto.MessageEnvelope.command)
  return payload_.command_;
}
inline ::agv::proto::AgvCommand* MessageEnvelope::release_command() {
  // @@protoc_insertion_point(field_release:agv.proto.MessageEnvelope.command)
  if (has_command()) {
    clear_has_payload();
    ::agv::proto::AgvCommand* temp = payload_.command_;
    payload_.command_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void MessageEnvelope::set_allocated_command(::agv::proto::AgvCommand* command) {
  clear_payload();
  if (command) {
    set_has_command();
    payload_.command_ = command;
  }
  // @@protoc_insertion_point(field_set_allocated:agv.proto.MessageEnvelope.command)
}

// optional .agv.proto.NavigationTask nav_task = 12;
inline bool MessageEnvelope::has_nav_task() const {
  return payload_case() == kNavTask;
}
inline void MessageEnvelope::set_has_nav_task() {
  _oneof_case_[0] = kNavTask;
}
inline void MessageEnvelope::clear_nav_task() {
  if (has_nav_task()) {
    delete payload_.nav_task_;
    clear_has_payload();
  }
}
inline  const ::agv::proto::NavigationTask& MessageEnvelope::nav_task() const {
  // @@protoc_insertion_point(field_get:agv.proto.MessageEnvelope.nav_task)
  return has_nav_task()
      ? *payload_.nav_task_
      : ::agv::proto::NavigationTask::default_instance();
}
inline ::agv::proto::NavigationTask* MessageEnvelope::mutable_nav_task() {
  if (!has_nav_task()) {
    clear_payload();
    set_has_nav_task();
    payload_.nav_task_ = new ::agv::proto::NavigationTask;
  }
  // @@protoc_insertion_point(field_mutable:agv.proto.MessageEnvelope.nav_task)
  return payload_.nav_task_;
}
inline ::agv::proto::NavigationTask* MessageEnvelope::release_nav_task() {
  // @@protoc_insertion_point(field_release:agv.proto.MessageEnvelope.nav_task)
  if (has_nav_task()) {
    clear_has_payload();
    ::agv::proto::NavigationTask* temp = payload_.nav_task_;
    payload_.nav_task_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void MessageEnvelope::set_allocated_nav_task(::agv::proto::NavigationTask* nav_task) {
  clear_payload();
  if (nav_task) {
    set_has_nav_task();
    payload_.nav_task_ = nav_task;
  }
  // @@protoc_insertion_point(field_set_allocated:agv.proto.MessageEnvelope.nav_task)
}

// optional .agv.proto.LatencyProbe latency_probe = 13;
inline bool MessageEnvelope::has_latency_probe() const {
  return payload_case() == kLatencyProbe;
}
inline void MessageEnvelope::set_has_latency_probe() {
  _oneof_case_[0] = kLatencyProbe;
}
inline void MessageEnvelope::clear_latency_probe() {
  if (has_latency_probe()) {
    delete payload_.latency_probe_;
    clear_has_payload();
  }
}
inline  const ::agv::proto::LatencyProbe& MessageEnvelope::latency_probe() const {
  // @@protoc_insertion_point(field_get:agv.proto.MessageEnvelope.latency_probe)
  return has_latency_probe()
      ? *payload_.latency_probe_
      : ::agv::proto::LatencyProbe::default_instance();
}
inline ::agv::proto::LatencyProbe* MessageEnvelope::mutable_latency_probe() {
  if (!has_latency_probe()) {
    clear_payload();
    set_has_latency_probe();
    payload_.latency_probe_ = new ::agv::proto::LatencyProbe;
  }
  // @@protoc_insertion_point(field_mutable:agv.proto.MessageEnvelope.latency_probe)
  return payload_.latency_probe_;
}
inline ::agv::proto::LatencyProbe* MessageEnvelope::release_latency_probe() {
  // @@protoc_insertion_point(field_release:agv.proto.MessageEnvelope.latency_probe)
  if (has_latency_probe()) {
    clear_has_payload();
    ::agv::proto::LatencyProbe* temp = payload_.latency_probe_;
    payload_.latency_probe_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void MessageEnvelope::set_allocated_latency_probe(::agv::proto::LatencyProbe* latency_probe) {
  clear_payload();
  if (latency_probe) {
    set_has_latency_probe();
    payload_.latency_probe_ = latency_probe;
  }
  // @@protoc_insertion_point(field_set_allocated:agv.proto.MessageEnvelope.latency_probe)
}

// optional .agv.proto.CommonResponse response = 21;
inline bool MessageEnvelope::has_response() const {
  return payload_case() == kResponse;
}
inline void MessageEnvelope::set_has_response() {
  _oneof_case_[0] = kResponse;
}
inline void MessageEnvelope::clear_response() {
  if (has_response()) {
    delete payload_.response_;
    clear_has_payload();
  }
}
inline  const ::agv::proto::CommonResponse& MessageEnvelope::response() const {
  // @@protoc_insertion_point(field_get:agv.proto.MessageEnvelope.response)
  return has_response()
      ? *payload_.response_
      : ::agv::proto::CommonResponse::default_instance();
}
inline ::agv::proto::CommonResponse* MessageEnvelope::mutable_response() {
  if (!has_response()) {
    clear_payload();
    set_has_response();
    payload_.response_ = new ::agv::proto::CommonResponse;
  }
  // @@protoc_insertion_point(field_mutable:agv.proto.MessageEnvelope.response)
  return payload_.response_;
}
inline ::agv::proto::CommonResponse* MessageEnvelope::release_response() {
  // @@protoc_insertion_point(field_release:agv.proto.MessageEnvelope.response)
  if (has_response()) {
    clear_has_payload();
    ::agv::proto::CommonResponse* temp = payload_.response_;
    payload_.response_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void MessageEnvelope::set_allocated_response(::agv::proto::CommonResponse* response) {
  clear_payload();
  if (response) {
    set_has_response();
    payload_.response_ = response;
  }
  // @@protoc_insertion_point(field_set_allocated:agv.proto.MessageEnvelope.response)
}

// optional .agv.proto.Heartbeat heartbeat = 22;
inline bool MessageEnvelope::has_heartbeat() const {
  return payload_case() == kHeartbeat;
}
inline void MessageEnvelope::set_has_heartbeat() {
  _oneof_case_[0] = kHeartbeat;
}
inline void MessageEnvelope::clear_heartbeat() {
  if (has_heartbeat()) {
    delete payload_.heartbeat_;
    clear_has_payload();
  }
}
inline  const ::agv::proto::Heartbeat& MessageEnvelope::heartbeat() const {
  // @@protoc_insertion_point(field_get:agv.proto.MessageEnvelope.heartbeat)
  return has_heartbeat()
      ? *payload_.heartbeat_
      : ::agv::proto::Heartbeat::default_instance();
}
inline ::agv::proto::Heartbeat* MessageEnvelope::mutable_heartbeat() {
  if (!has_heartbeat()) {
    clear_payload();
    set_has_heartbeat();
    payload_.heartbeat_ = new ::agv::proto::Heartbeat;
  }
  // @@protoc_insertion_point(field_mutable:agv.proto.MessageEnvelope.heartbeat)
  return payload_.heartbeat_;
}
inline ::agv::proto::Heartbeat* MessageEnvelope::release_heartbeat() {
  // @@protoc_insertion_point(field_release:agv.proto.MessageEnvelope.heartbeat)
  if (has_heartbeat()) {
    clear_has_payload();
    ::agv::proto::Heartbeat* temp = payload_.heartbeat_;
    payload_.heartbeat_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void MessageEnvelope::set_allocated_heartbeat(::agv::proto::Heartbeat* heartbeat) {
  clear_payload();
  if (heartbeat) {
    set_has_heartbeat();
    payload_.heartbeat_ = heartbeat;
  }
  // @@protoc_insertion_point(field_set_allocated:agv.proto.MessageEnvelope.heartbeat)
}

inline bool MessageEnvelope::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void MessageEnvelope::clear_has_payload() {
  _oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline MessageEnvelope::PayloadCase MessageEnvelope::payload_case() const {
  return MessageEnvelope::PayloadCase(_oneof_case_[0]);
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace agv

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
